import javax.swing.*;
import java.awt.*;

public class Menu extends JFrame {
    private JPanel root;
    private JPanel Startfolie;
    private JButton button1;
    private JButton button2;
    private JPanel panel2;


    public Menu() {
        super();
        add(root);
        setVisible(true);
        root.setVisible(true);
        setSize(400, 400);
        Startfolie.setVisible(true);
        panel2.setVisible(false);

      /*  try {
            PreparedStatement ps = Connector.getConn().prepareStatement("SELECT * FROM halle");
            ResultSet result = ps.executeQuery();
            while (result.next()) {
                textField1.setText(textField1.getText() + result.getString(2) + ", ");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }*/

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new CardLayout(0, 0));
        Startfolie = new JPanel();
        Startfolie.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.add(Startfolie, "Card1");
        registrierenButton = new JButton();
        registrierenButton.setText("Button1");
        Startfolie.add(registrierenButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.add(panel2, "Card2");
        anmeldenButton = new JButton();
        anmeldenButton.setText("Button2");
        panel2.add(anmeldenButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
